version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    restart: unless-stopped
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - elk_data:/usr/share/elasticsearch/data/
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - ${ES_PORT}:9200
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      # - xpack.monitoring.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
    #     ]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 120
    networks:
      - elastic

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    restart: unless-stopped
    depends_on:
      - elasticsearch
    ports:
      - ${LOGSTASH_PORT}:5044
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ls_data:/usr/share/logstash/data
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    restart: unless-stopped
    depends_on:
      - elasticsearch
    labels:
      co.elastic.logs/module: kibana
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - kb_data:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    mem_limit: ${MEM_LIMIT}
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
    #     ]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 120
    networks:
      - elastic

  filebeat:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
    restart: unless-stopped
    user: root
    command: filebeat -e -strict.perms=false
    depends_on:
      - elasticsearch
      - kibana
    labels:
      co.elastic.logs/enabled: "false"
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/syslog:/var/log/syslog:ro
      - /var/log/auth.log:/var/log/auth.log:ro
    networks:
      - elastic
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

networks:
  elastic:
    driver: bridge

volumes:
  elk_data:
  ls_data:
  kb_data: